<?php require('template/header.phtml'); ?>

    <main>
        <!-- Hero Section -->
        <section class="hero">
            <div class="hero-text">
                <h1>Local Facilities, <br>Global Impact</h1>
                <p>ecoBuddy connects communities with eco-friendly services such as recycling bins, e-bike stations, and vehicle charging points across Manchester.</p>
                <a href="crud.php" class="btn-home-page">EXPLORE FACILITIES</a>
            </div>

            <!-- business slogan pic-->
            <div class="logo-container">
                <img src="Views/images/EcoBuddy (1).png" alt="logo" class="logo">
            </div>
        </section>

        <!-- About Section -->
        <section class="about container">
            <div class="row align-items-center">
                <div class="about-text">
                    <h2>About ecoBuddy</h2>
                    <p>At ecoBuddy, we envision a world where sustainability is effortless and accessible to everyone. Our platform connects you to eco-friendly facilities in your local area, encouraging small yet impactful steps toward a cleaner, more sustainable planet.</p>

                    <p>From recycling stations and electric vehicle charging points to community compost bins and bike-share hubs, ecoBuddy helps you easily locate and engage with facilities that support sustainable living.</p>

                    <p>ecoBuddy is more than just a tool – it’s a community-driven initiative designed to promote greener habits and collective action. By contributing to and updating facility information, users like you help shape a better future for everyone.</p>
                </div>

                <div class="uk-map">
                    <img src="Views/images/map.png" alt="map Image" class="map-image">
                </div>
            </div>
        </section>

        <!-- Login Section -->
        <section class="full-width-login-section">
            <h2>Ready to Contribute?</h2>
            <p>Log in to manage eco-friendly facilities, change status and explore more.</p>
            <a href="login.php" class="btn-home-page">Log In</a>
        </section>
    </main>

<?php require('template/footer.phtml'); ?>